(()=>{const start=()=>{const box=document.getElementById("pdfCanvasWrap"),canvas=document.getElementById("pdfCanvas"),prev=document.getElementById("pdfPrev"),next=document.getElementById("pdfNext");if(!box||!canvas||!prev||!next)return;canvas.classList.add("pdf-canvas");const prevAction=prev.onclick,nextAction=next.onclick;let busy=false,lastTouch=0,audio=null;
const paperSound=()=>{try{const AC=window.AudioContext||window.webkitAudioContext;if(!AC)return;if(!audio)audio=new AC;if(audio.state==="suspended")audio.resume();const now=audio.currentTime;const buffer=audio.createBuffer(1,audio.sampleRate*.16,audio.sampleRate),data=buffer.getChannelData(0);for(let i=0;i<data.length;i++){const t=i/data.length;data[i]=(Math.random()*2-1)*(1-t)*.45}
const src=audio.createBufferSource();src.buffer=buffer;const filter=audio.createBiquadFilter();filter.type="bandpass";filter.frequency.value=1250;filter.Q.value=.7;const gain=audio.createGain();gain.gain.setValueAtTime(.0001,now);gain.gain.exponentialRampToValueAtTime(.18,now+.018);gain.gain.exponentialRampToValueAtTime(.0001,now+.14);src.connect(filter).connect(gain).connect(audio.destination);src.start(now);src.stop(now+.16);
const osc=audio.createOscillator(),og=audio.createGain();osc.type="sine";osc.frequency.setValueAtTime(170,now);osc.frequency.exponentialRampToValueAtTime(85,now+.15);og.gain.setValueAtTime(.0001,now);og.gain.exponentialRampToValueAtTime(.035,now+.02);og.gain.exponentialRampToValueAtTime(.0001,now+.15);osc.connect(og).connect(audio.destination);osc.start(now);osc.stop(now+.16)}catch(e){}};
const turn=(dir)=>{const action=dir<0?prevAction:nextAction,button=dir<0?prev:next;if(busy||button.disabled||typeof action!=="function")return false;busy=true;paperSound();canvas.classList.remove("flip-next","flip-prev");void canvas.offsetWidth;canvas.classList.add(dir<0?"flip-prev":"flip-next");setTimeout(()=>{try{action.call(button)}catch(e){}},220);setTimeout(()=>{canvas.classList.remove("flip-next","flip-prev");busy=false},520);return true};
const onClick=e=>{if(Date.now()-lastTouch<600)return;if(e.target.closest(".pdf-toolbar"))return;const r=box.getBoundingClientRect();turn(e.clientX<r.left+r.width/2?-1:1)};
box.addEventListener("click",onClick);
let touchX=0;box.addEventListener("touchstart",e=>{touchX=e.changedTouches[0].clientX;lastTouch=Date.now()},{passive:true});box.addEventListener("touchend",e=>{const dx=e.changedTouches[0].clientX-touchX;lastTouch=Date.now();if(Math.abs(dx)>50)turn(dx<0?1:-1)},{passive:true});
window.addEventListener("keydown",e=>{const modal=document.getElementById("modal");if(!modal||modal.classList.contains("hidden"))return;if(e.key==="ArrowRight")turn(1);else if(e.key==="ArrowLeft")turn(-1)});
};if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",start,{once:true});else start()})();