(()=>{const start=()=>{const box=document.getElementById("pdfCanvasWrap"),canvas=document.getElementById("pdfCanvas"),prev=document.getElementById("pdfPrev"),next=document.getElementById("pdfNext");if(!box||!canvas||!prev||!next)return;const prevAction=prev.onclick,nextAction=next.onclick;let busy=false,lastTouch=0,flipAudio=null;
const unlockAudio=()=>{try{const p=flipAudio?.play();if(p){p.then(()=>{flipAudio.pause();flipAudio.currentTime=0}).catch(()=>{})}}catch(e){}};
flipAudio=new Audio("./audio/page-flip-smooth.mp3?v=20260920-2305");flipAudio.preload="auto";flipAudio.volume=.42;
const playFlipSound=()=>{if(!flipAudio)return;try{flipAudio.currentTime=0;const p=flipAudio.play();if(p&&p.catch)p.catch(()=>{})}catch(e){}};
const animate=dir=>{const action=dir<0?prevAction:nextAction,button=dir<0?prev:next;if(busy||button.disabled||typeof action!=="function")return false;busy=true;
const old=canvas.cloneNode(true);old.removeAttribute("id");old.className="pdf-page-old "+(dir>0?"old-next":"old-prev");old.setAttribute("aria-hidden","true");
const curl=document.createElement("div");curl.className="pdf-page-curl "+(dir>0?"next":"prev");curl.setAttribute("aria-hidden","true");
const cs=getComputedStyle(canvas),r=canvas.getBoundingClientRect(),br=box.getBoundingClientRect();
old.width=canvas.width;old.height=canvas.height;old.style.width=cs.width;old.style.height=cs.height;old.style.left=(r.left-br.left+box.scrollLeft)+"px";old.style.top=(r.top-br.top+box.scrollTop)+"px";
curl.style.left=old.style.left;curl.style.top=old.style.top;curl.style.height=cs.height;curl.style.width=Math.max(70,Math.round(parseFloat(cs.width||"800")*.24))+"px";
box.appendChild(old);box.appendChild(curl);
try{action.call(button)}catch(e){}
requestAnimationFrame(()=>playFlipSound());
const cleanup=()=>{old.remove();curl.remove();busy=false};old.addEventListener("animationend",cleanup,{once:true});setTimeout(cleanup,1000);return true};
box.addEventListener("pointerdown",unlockAudio,{passive:true});
box.addEventListener("click",e=>{if(Date.now()-lastTouch<650||e.target.closest(".pdf-toolbar"))return;const r=box.getBoundingClientRect();animate(e.clientX<r.left+r.width/2?-1:1)});
let touchX=0;box.addEventListener("touchstart",e=>{touchX=e.changedTouches[0].clientX;lastTouch=Date.now();unlockAudio()},{passive:true});
box.addEventListener("touchend",e=>{const dx=e.changedTouches[0].clientX-touchX;lastTouch=Date.now();if(Math.abs(dx)>48)animate(dx<0?1:-1)},{passive:true});
window.addEventListener("keydown",e=>{const modal=document.getElementById("modal");if(!modal||modal.classList.contains("hidden"))return;if(e.key==="ArrowRight")animate(1);else if(e.key==="ArrowLeft")animate(-1)});
};if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",start,{once:true});else start()})();