plugins {
    id 'com.android.application'
}

android {
    namespace 'com.jd.studynote'
    compileSdk 36

    defaultConfig {
        applicationId 'com.jd.studynote'
        minSdk 26
        targetSdk 36
        versionCode 2
        versionName '1.1.0'
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    buildTypes {
        release {
            minifyEnabled false
            debuggable false
            signingConfig signingConfigs.debug
        }
    }
}
