create schema if not exists extensions;
create extension if not exists pg_trgm with schema extensions;

create table if not exists public.categories (
  id bigint generated by default as identity primary key,
  name text not null unique,
  slug text not null unique,
  icon text not null default '✦',
  description text,
  created_at timestamptz not null default now()
);

create table if not exists public.topics (
  id bigint generated by default as identity primary key,
  slug text not null unique,
  title text not null,
  deck text not null,
  short_answer text not null,
  body text not null,
  why_it_matters text,
  remember text,
  mechanism text,
  misconception text,
  next_questions text[] not null default '{}',
  category_id bigint not null references public.categories(id) on delete restrict,
  tag text not null,
  reading_minutes numeric(4,1) not null default 2,
  tone text not null default 'violet',
  source_name text,
  source_url text,
  verified_at timestamptz,
  published boolean not null default false,
  featured boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists topics_category_idx on public.topics(category_id);
create index if not exists topics_published_idx on public.topics(published, featured desc, updated_at desc);
create index if not exists topics_title_trgm_idx on public.topics using gin(title gin_trgm_ops);

create table if not exists public.daily_lessons (
  id bigint generated by default as identity primary key,
  lesson_date date not null unique,
  headline text not null,
  intro text,
  topic_ids bigint[] not null default '{}',
  created_at timestamptz not null default now()
);

create table if not exists public.newsletter_subscribers (
  id bigint generated by default as identity primary key,
  email text not null unique,
  created_at timestamptz not null default now()
);

alter table public.categories enable row level security;
alter table public.topics enable row level security;
alter table public.daily_lessons enable row level security;
alter table public.newsletter_subscribers enable row level security;

create policy "Public can read categories" on public.categories
  for select to anon, authenticated using (true);
create policy "Public can read published topics" on public.topics
  for select to anon, authenticated using (published = true);
create policy "Public can read daily lessons" on public.daily_lessons
  for select to anon, authenticated using (true);
create policy "Public can subscribe" on public.newsletter_subscribers
  for insert to anon, authenticated with check (
    email = lower(trim(email))
    and email ~* '^[^\\s@]+@[^\\s@]+\\.[^\\s@]+$'
    and length(email) <= 254
  );

revoke all on public.newsletter_subscribers from anon, authenticated;
grant insert on public.newsletter_subscribers to anon, authenticated;
grant select on public.categories to anon, authenticated;
grant select on public.topics to anon, authenticated;
grant select on public.daily_lessons to anon, authenticated;
